import type { PrintConfig } from './types'

export const DEFAULT_PRINT_CONFIG: PrintConfig = {
  pageSize: 'A5',
  pageOrientation: 'portrait',
  printMargin: '0',
  pageBackground: '#ffffff00',
  lineBorderColor: '#d6d6d6',
  lineBorderWidth: 1,
  screenMaxWidth: 1100,
  printPagePadding: '0',
  rowHeight: 28,
  rowGap: 4,
  scaleFontSize: 10,
  headerTextEn: 'Your results',
  headerTextDe: 'Deine Ergebnisse',
  headerFontSize: 22,
  lineNumberWidth: 34,
  lineNumberFontSize: 12,
  legendFontSize: 11,
  pointColor: '#000000',
  historicalPointSize: 4,
  correctPointSize: 10,
  userPointSize: 16,
}
