import type { PrintConfig } from './types'

export const DEFAULT_PRINT_CONFIG: PrintConfig = {
  pageSize: 'A5',
  pageOrientation: 'portrait',
  printMargin: '0',
  pageBackground: '#ffffff00',
  lineBorderColor: '#d6d6d6',
  lineBorderWidth: 1,
  screenMaxWidth: 1100,
  printPagePadding: '0',
  rowHeight: 28,
  rowGap: 4,
  barWidth: 5,
  minBarWidth: 1,
  maxBarWidth: 5,
  barTopOffset: 1,
  scaleFontSize: 10,
  headerTextEn: 'Your results',
  headerTextDe: 'Deine Ergebnisse',
  headerFontSize: 22,
  lineNumberWidth: 34,
  lineNumberFontSize: 12,
  legendFontSize: 11,
  historicalBarWidth: 1,
  userBarWidth: 10,
  correctBarWidth: 5,
  historicalBarColor: '#6d6d6d',
  correctBarColor: '#111111',
  altAColor: '#51b7de',
  altBColor: '#0e5ea6',
  defaultLineColor: '#9f9f9f',
  correctAnswerColor: '#d8d8d8',
  lineColors: [
    '#0033ff', // blue
    '#1a47ff',
    '#3361ff',
    '#4d7aff',
    '#6694ff',
    '#80adff',
    '#ffb3b3',
    '#ff9999',
    '#ff8080',
    '#ff6666',
    '#ff3333', // red
    '#ff3333', // repeat for 13 lines
    '#ff3333',
    '#ff3333',
  ],
}
