import type { PrintConfig } from './types'

export const DEFAULT_PRINT_CONFIG: PrintConfig = {
  pageSize: 'A5',
  pageOrientation: 'portrait',
  printMargin: '0',
  pageBackground: '#ffffff00',
  lineBorderColor: '#d6d6d6',
  lineBorderWidth: 1,
  screenMaxWidth: 1100,
  printPagePadding: '0',
  rowHeight: 28,
  rowGap: 5,
  scaleFontSize: 10,
  headerTextEn: '',
  headerTextDe: '',
  headerFontSize: 22,
  lineNumberWidth: 18,
  lineNumberFontSize: 8,
  legendFontSize: 11,
  pointColor: '#000000',
  historicalPointSize: 4,
  correctPointSize: 10,
  userPointSize: 16,
}
